name: Python build

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Docker Tag
        required: true
        default: v1

jobs:
    build:
        name: python build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-python@v6
              with:
                python-version: '3.13'

            - name: run python app
              run: python ./Practice/test.py

            - name: Docker Version
              run: docker --version
            
            - name: Build Docker Image
              run: docker build -t python-demo:${{github.action.inputs.image_tag}}.${{github.run_number}} ./Practice/.