name: Python build

on:
  workflow_dispatch:
    inputs:
        image_tag:
            description: Docker Tag
            required: true
            default: v1
      

jobs:
    buil_python:
        name: Build a python application
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'
            
            - name: Upgrade pip
              run: python -m pip install --upgrade pip
            
            - name: install dependencies
              run: pip install -r ./Practice/requirements.txt
        
            - name: run unit testes
              run: pytest Practice -v

            - name: Docker Version
              run: docker --version
            
            - name: Build Docker Image
              run: docker build -t python-demo:${{github.event.inputs.image_tag}}.${{github.run_number}} ./Practice/.