name: Execute with parametes

on :
  workflow_dispatch:
    inputs:
        environment:
            description: "deployment Environment"
            required: true
            type: choice
            options:
                - dev
                - prod
                - test
        deploy:
            description: "Deploy Application?"
            required: true
            type: boolean
        
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Print selected environemtn
          run: echo " selected environment is ${{ github.event.inputs.environment}}"
        
        - name: Print deploy option
          run: echo 'Prints deploy option is ${{github.event.inputs.deploy}}'